language: node_js
node_js:
  - lts/*

sudo: required
services:
  - docker

before_install:
  - docker build -t gabrieldsrosa/hello-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gabrieldsrosa/hello-docker-react npm run test
